
-- Conecte-se ao banco:
-- \c SISTEMA_GERENCIADOR_INFLUENCER

CREATE TABLE TB_MARCA (
	ID_MARCA SERIAL NOT NULL,
	NM_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
	CD_CNPJ VARCHAR(14) NOT NULL,
	NM_CONTATO VARCHAR(255) NOT NULL,
	CONSTRAINT PK_TB_MARCA PRIMARY KEY (ID_MARCA),
	CONSTRAINT UK_TB_MARCA_CNPJ UNIQUE (CD_CNPJ)
);

CREATE TABLE TB_NICHO (
	ID_NICHO SERIAL NOT NULL,
	NM_NICHO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TB_NICHO PRIMARY KEY (ID_NICHO),
	CONSTRAINT UK_TB_NICHO_NOME UNIQUE(NM_NICHO)
);

CREATE TABLE TB_INFLUENCIADOR (
	ID_INFLUENCIADOR SERIAL NOT NULL,
	NM_CIVIL VARCHAR(100) NOT NULL,
	NM_ARTISTICO VARCHAR(100) NULL,
	DS_EMAIL_CONTATO VARCHAR(255) NOT NULL,
	DS_DADOS_BANCARIOS TEXT NULL,
	CD_CPF VARCHAR(11) NOT NULL,
	CONSTRAINT PK_TB_INFLUENCIADOR PRIMARY KEY (ID_INFLUENCIADOR),
	CONSTRAINT UK_TB_INFLUENCIADOR_CPF UNIQUE(CD_CPF),
	CONSTRAINT UK_TB_INFLUENCIADOR_EMAIL UNIQUE(DS_EMAIL_CONTATO)
);

CREATE TABLE TB_PLATAFORMA (
	ID_PLATAFORMA SERIAL NOT NULL,
	NM_PLATAFORMA VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TB_PLATAFORMA PRIMARY KEY (ID_PLATAFORMA),
	CONSTRAINT UK_TB_PLATAFORMA_NOME UNIQUE(NM_PLATAFORMA)
);

CREATE TABLE TH_CAMPANHA (
	ID_CAMPANHA SERIAL NOT NULL,
	NM_CAMPANHA VARCHAR(255) NOT NULL,
	DS_DESCRICAO TEXT NULL,
	DT_INICIO DATE NOT NULL,
	DT_FIM DATE NULL,
	VL_ORCAMENTO NUMERIC(10, 2) NOT NULL,
	ST_CAMPANHA VARCHAR(50) NULL,
	ID_MARCA INT NOT NULL,
	CONSTRAINT PK_TH_CAMPANHA PRIMARY KEY (ID_CAMPANHA),
	CONSTRAINT FK_THCAMPANHA_TBMARCA FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCA (ID_MARCA)
);

CREATE TABLE TB_PERFIL_SOCIAL(
	ID_PERFIL_SOCIAL SERIAL NOT NULL,
	CD_URL VARCHAR(2048) NOT NULL,
	ID_INFLUENCIADOR INT NOT NULL,
	ID_PLATAFORMA INT NOT NULL,
	CONSTRAINT PK_TB_PERFIL_SOCIAL PRIMARY KEY (ID_PERFIL_SOCIAL),
	CONSTRAINT UK_TB_PERFIL_SOCIAL_URL UNIQUE(CD_URL),
	CONSTRAINT FK_TBPERFILSOCIAL_TBINFLUENCIADOR FOREIGN KEY (ID_INFLUENCIADOR) REFERENCES TB_INFLUENCIADOR (ID_INFLUENCIADOR),
	CONSTRAINT FK_TBPERFILSOCIAL_TBPLATAFORMA FOREIGN KEY (ID_PLATAFORMA) REFERENCES TB_PLATAFORMA (ID_PLATAFORMA)
);

CREATE TABLE RL_INFLUENCIADOR_NICHO (
	ID_INFLUENCIADOR INT NOT NULL,
	ID_NICHO INT NOT NULL,
	CONSTRAINT FK_RLINFLUENCIADORNICHO_TBINFLUENCIADOR FOREIGN KEY (ID_INFLUENCIADOR) REFERENCES TB_INFLUENCIADOR (ID_INFLUENCIADOR),
	CONSTRAINT FK_RLINFLUENCIADORNICHO_TBNICHO FOREIGN KEY (ID_NICHO) REFERENCES TB_NICHO (ID_NICHO),
	CONSTRAINT PK_RL_INFLUENCIADOR_NICHO PRIMARY KEY (ID_INFLUENCIADOR, ID_NICHO)
);

CREATE TABLE RL_CONTRATO (
	ID_CONTRATO SERIAL NOT NULL,
	DS_CLAUSULA_EXCLUSIVIDADE TEXT NULL,
	DT_ASSINATURA DATE NOT NULL,
	DS_MODELO_PAGAMENTO TEXT NOT NULL,
	VL_TOTAL NUMERIC(10, 2) NOT NULL,
	ID_INFLUENCIADOR INT NOT NULL,
	ID_CAMPANHA INT NOT NULL,
	CONSTRAINT PK_RL_CONTRATO PRIMARY KEY (ID_CONTRATO),
	CONSTRAINT FK_RLCONTRATO_TBINFLUENCIADOR FOREIGN KEY (ID_INFLUENCIADOR) REFERENCES TB_INFLUENCIADOR (ID_INFLUENCIADOR),
	CONSTRAINT FK_RLCONTRATO_THCAMPANHA FOREIGN KEY (ID_CAMPANHA) REFERENCES TH_CAMPANHA (ID_CAMPANHA)
);

CREATE TABLE TB_ITEM_CONTRATO(
	ID_ITEM_CONTRATO SERIAL NOT NULL,
	DS_ENTREGA TEXT NULL,
	DT_PRAZO DATE NOT NULL,
	ST_STATUS VARCHAR(50) NULL,
	ID_CONTRATO INT NOT NULL,
	CONSTRAINT PK_TB_ITEM_CONTRATO PRIMARY KEY (ID_ITEM_CONTRATO),
	CONSTRAINT FK_TBITEMCONTRATO_RLCONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES RL_CONTRATO (ID_CONTRATO)
);

CREATE TABLE TB_TRANSACAO_FINANCEIRA(
	ID_TRANSACAO_FINANCEIRA SERIAL NOT NULL,
	TP_TIPO VARCHAR(100) NOT NULL,
	VL_VALOR NUMERIC(10, 2) NOT NULL,
	DT_VENCIMENTO DATE NULL,
	DT_QUITACAO DATE NULL,
	ST_STATUS VARCHAR(50) NULL,
	ID_CONTRATO INT NOT NULL,
	CONSTRAINT PK_TB_TRANSACAO_FINANCEIRA PRIMARY KEY (ID_TRANSACAO_FINANCEIRA),
	CONSTRAINT FK_TBTRANSACAOFINANCEIRA_RLCONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES RL_CONTRATO (ID_CONTRATO)
);

CREATE TABLE TH_METRICA(
	ID_METRICA SERIAL NOT NULL,
	DT_COLETA DATE NOT NULL,
	NR_SEGUIDORES INT NOT NULL,
	VL_TAXA_ENGAJAMENTO NUMERIC(5, 2) NOT NULL,
	ID_PERFIL_SOCIAL INT NOT NULL,
	CONSTRAINT PK_TH_METRICA PRIMARY KEY (ID_METRICA),
	CONSTRAINT FK_THMETRICA_TBPERFILSOCIAL FOREIGN KEY (ID_PERFIL_SOCIAL) REFERENCES TB_PERFIL_SOCIAL (ID_PERFIL_SOCIAL)
);

CREATE TABLE TL_REGISTRO_COMUNICACAO(
	ID_REGISTRO_COMUNICACAO SERIAL NOT NULL,
	DT_INTERACAO DATE NOT NULL,
	DS_PARTICIPANTES TEXT NOT NULL,
	DS_RESUMO TEXT NULL,
	ID_CAMPANHA INT NOT NULL,
	CONSTRAINT PK_TL_REGISTRO_COMUNICACAO PRIMARY KEY (ID_REGISTRO_COMUNICACAO),
	CONSTRAINT FK_TLREGISTROCOMUNICACAO_THCAMPANHA FOREIGN KEY (ID_CAMPANHA) REFERENCES TH_CAMPANHA (ID_CAMPANHA)
);

