/**************************************************************
* SCRIPT DDL - PLANO DE INDEXAÇÃO (OTIMIZAÇÃO)
**************************************************************/

CREATE INDEX IDX_THCAMPANHA_MARCA ON TH_CAMPANHA (ID_MARCA);
CREATE INDEX IDX_TBPERFILSOCIAL_INFLU ON TB_PERFIL_SOCIAL (ID_INFLUENCIADOR);
CREATE INDEX IDX_TBPERFILSOCIAL_PLAT ON TB_PERFIL_SOCIAL (ID_PLATAFORMA);
CREATE INDEX IDX_RLCONTRATO_INFLU ON RL_CONTRATO (ID_INFLUENCIADOR);
CREATE INDEX IDX_RLCONTRATO_CAMP ON RL_CONTRATO (ID_CAMPANHA);
CREATE INDEX IDX_TBITEMCONTRATO_CONTRATO ON TB_ITEM_CONTRATO (ID_CONTRATO);
CREATE INDEX IDX_TBTRANSFINAN_CONTRATO ON TB_TRANSACAO_FINANCEIRA (ID_CONTRATO);
CREATE INDEX IDX_THMETRICA_PERFIL ON TH_METRICA (ID_PERFIL_SOCIAL);
CREATE INDEX IDX_TLREGCOMUN_CAMPANHA ON TL_REGISTRO_COMUNICACAO (ID_CAMPANHA);
CREATE INDEX IDX_TBITEMCONTRATO_STATUS_PENDENTE ON TB_ITEM_CONTRATO (ST_STATUS)
WHERE ST_STATUS <> 'Concluida';
CREATE INDEX IDX_THMETRICA_NRSEGUIDORES ON TH_METRICA (nr_seguidores);
CREATE INDEX IDX_THMETRICA_COLETA ON TH_METRICA (DT_COLETA);
CREATE INDEX IDX_RLCONTRATO_VALOR ON RL_CONTRATO (VL_TOTAL DESC);





